package:
  name: pymcce
  version: 1.0.0

source:
  path: ../../

requirements:
  build:
    - python >=2.7
    - setuptools

  run:
    - python >=2.7
    - numpy
    - scipy
    - mdtraj
    - parmed

about:
  home: https://github.com/kamran-haider
  license: MIT
  summary: Python tools for analysis of MCCE simulations
